apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: media-ingress
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`plex.*`)
      services:
        - kind: Service
          name: plex
          port: 32400
    - kind: Rule
      match: HostRegexp(`jackett.*`)
      services:
        - kind: Service
          name: jackett
          port: 9117
    - kind: Rule
      match: HostRegexp(`radarr.*`)
      services:
        - kind: Service
          name: radarr
          port: 7878
    - kind: Rule
      match: HostRegexp(`sonarr.*`)
      services:
        - kind: Service
          name: sonarr
          port: 8989
    - kind: Rule
      match: HostRegexp(`qbittorrent.*`)
      services:
        - kind: Service
          name: qbittorrent
          port: 8080
