apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: media-ingress
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`plex.local.io`)
      services:
        - kind: Service
          name: plex
          port: 32400
    - kind: Rule
      match: Host(`jackett.local.io`)
      services:
        - kind: Service
          name: jackett
          port: 9117
    - kind: Rule
      match: Host`radarr.local.io`)
      services:
        - kind: Service
          name: radarr
          port: 7878
    - kind: Rule
      match: Host(`sonarr.local.io`)
      services:
        - kind: Service
          name: sonarr
          port: 8989
    - kind: Rule
      match: Host(`qbittorrent.local.io`)
      services:
        - kind: Service
          name: qbittorrent
          port: 8080
