apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-smarthome-pv
  namespace: smarthome
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-smarthome-pvc
  namespace: smarthome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-frigate-pv
  namespace: smarthome
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /media/frigate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-frigate-pvc
  namespace: smarthome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""